server:
  port: 8888
#Pour afficher les configs tapez ces utls
#http://localhost:8888/client-service/main
#http://localhost:8888/uaa-service/main
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/richy21/microservice-config.git
  application:
    name: CONFIG-SERVICE
#Ce service ne va pas senregistre